---
- name: Python - Development Tools
  become: true
  package:
    update_cache: yes
    state: "{{ python.state }}"
    name: "{{ item }}"
  loop:
    - virtualenv
    - pipenv
    - python3-dev
    - python3-pip
    - python3-setuptools
    - python3-pexpect # needed for expect: (see homebrew install)
    - python3-apt