---
# .rc and .profile files

- name: Bash - copy .profile
  copy:
    src: .profile
    dest: "{{ lookup('env', 'HOME') }}/.profile"    

- name: Bash - copy .bashrc
  copy:
    src: .bashrc
    dest: "{{ lookup('env', 'HOME') }}/.bashrc"

- name: Zsh - copy .zprofile
  copy:
    src: .zprofile
    dest: "{{ lookup('env', 'HOME') }}/.zprofile"

- name: Zsh - copy .zshrc
  copy:
    src: .zshrc
    dest: "{{ lookup('env', 'HOME') }}/.zshrc"

#----------------#

- name: ~/.config/shell/ - copy common_config
  copy:
    src: .config/shell/common_config
    dest: "{{ lookup('env', 'HOME') }}/.config/shell/common_config"

- name: ~/.config/shell/ - copy bash_config
  copy:
    src: .config/shell/bash_config
    dest: "{{ lookup('env', 'HOME') }}/.config/shell/bash_config"

- name: ~/.config/shell/ - copy zsh_config
  copy:
    src: .config/shell/zsh_config
    dest: "{{ lookup('env', 'HOME') }}/.config/shell/zsh_config"

- name: ~/.config/ - copy starship.toml
  copy:
    src: .config/starship.toml
    dest: "{{ lookup('env', 'HOME') }}/.config/starship.toml"    
