
# vim
- name: vim autoload directory
  file:
    path: "{{ lookup('env', 'HOME') }}/.vim/autoload"
    state: directory

- name: vim - vim plug - remove existing
  file:
    path: "{{ lookup('env', 'HOME') }}/.vim/autoload/plug.vim"
    state: absent
  when: vim.plug.remove_existing == true

- stat: path="{{ lookup('env', 'HOME') }}/.vim/autoload/plug.vim"
  register: vim_plug

- name: vim plug for vim
  get_url:
    url: "{{ vim.plug.install }}"
    dest: "{{ lookup('env', 'HOME') }}/.vim/autoload"
  when:
    not vim_plug.stat.exists

- name: vimrc 
  copy:
    src: .vim/vimrc
    dest: "{{ lookup('env', 'HOME') }}/.vim/vimrc"

# nvim
# - name: nvim config directory
#   file:
#     path: "{{ lookup('env', 'HOME') }}/.config/nvim"
#     state: directory

# - name: 
#   copy:
#     src: .config/nvim/init.vim    
#     dest: "{{ lookup('env', 'HOME') }}/.config/nvim/init.vim"

