---
- name: Lazygit - Remove exisiting version
  file:
    state: absent
    path: "{{ lookup('env', 'HOME') }}/go/bin/lazygit"
  when: go_tools.lazygit.remove_existing == true
  environment:
    PATH: "/usr/local/go/bin:{{ ansible_env.PATH }}"

- stat: path="{{ lookup('env', 'HOME') }}/go/bin/lazygit"
  register: lazygit_bin

- name: Lazygit - Install using go get {{ go_tools.lazygit.install }}
  shell: "go install {{ go_tools.lazygit.install }}"
  when: not lazygit_bin.stat.exists
  environment:
    PATH: "/usr/local/go/bin:{{ ansible_env.PATH }}"
