---
# IMPORTANT: Make sure Rust, Cargo are installed and available in the shell

- name: "cargo - Install tools"
  shell: "cargo {{ cargo.operation }} {{ item }}"
  loop: "{{ cargo.tools }}"
  when:
    - cargo.operation == 'install'
  environment:
    PATH: "{{ lookup('env', 'HOME') }}/.cargo/bin:{{ ansible_env.PATH }}"
    OPENSSL_DIR: "/usr/bin/openssl"

- name: "cargo - Uninstall tools"
  shell: "cargo {{ cargo.operation }} {{ item }}"
  loop: "{{ cargo.tools }}"
  when:
    - cargo.operation == 'uninstall'
  environment:
    PATH: "{{ lookup('env', 'HOME') }}/.cargo/bin:{{ ansible_env.PATH }}"
