---
# cht.sh
# https://github.com/chubin/cheat.sh

- name: Cht.sh - check if it already exists
  stat:
    path: "{{ lookup('env', 'HOME') }}/.local/bin/cht.sh"
  register: chtsh_bin

# - debug: var=chtsh_bin

- name: Cht.sh - Download
  get_url:
    url: https://cht.sh/:cht.sh
    dest: "{{ lookup('env', 'HOME') }}/.local/bin/cht.sh"
    mode: a+x
  when: not chtsh_bin.stat.exists or chtsh.reinstall == true

# lf
# https://github.com/gokcehan/lf/releases/download/r24/lf-linux-arm64.tar.gz

- name: lf - Remove exisiting version
  file:
    state: absent
    path: "{{ lookup('env', 'HOME') }}/.local/bin/lf"
  when: lf.remove_existing == true

- stat: path="{{ lookup('env', 'HOME') }}/.local/bin/lf"
  register: lf_bin

- debug: msg="https://github.com/gokcehan/lf/releases/download/{{ lf.ver }}/lf-{{ target.platform }}-{{ target.arch }}.tar.gz"

- when: not lf_bin.stat.exists
  name: "lf - Download and Unarchive to ~/.local/bin"
  unarchive:
    src: "https://github.com/gokcehan/lf/releases/download/{{ lf.ver }}/lf-{{ target.platform }}-{{ target.arch }}.tar.gz"
    dest: "{{ lookup('env', 'HOME') }}/.local/bin"
    mode: 0755
    remote_src: yes
