# Tools usually pre-installed on Debian
# - whereis      
# - which
# - ldd
# - diff
# - cat
# - tac      
# - free
# - sed
# - awk
# - hostname

common:
  dev:
    state: present
    tools:
      - ca-certificates
      - dpkg
      - file
      - gnupg # needed for docker
      - htop
      - httpie
      - jq
      - lsb-release      
      # - neovim # use newer ver
      - openssh-client
      - procps
      - ripgrep
      - rsync
      - software-properties-common # apt-add-repo
      - spell
      - tmux
      - tree
      - unzip
      - vim
      - wamerican
      - wbritish
      - xclip
      - zip
      - neofetch
      - ffmpeg     
      - lolcat      
      - libssl-dev
      - pkg-config
      - bat
      - moreutils
  net:
    state: present
    tools:    
      - dnsutils # dig, nslookup, nsupdate
      - whois
      - traceroute  
  fun:
    state: present
    tools:
      - figlet
      - cowsay # also used in ansible output 
      - cmatrix

