# fallback ver = if latest version check fails
# remove_existing checks per lang / framework

rust:
  remove_existing: false
  rustup_init: https://sh.rustup.rs

deno:
  remove_existing: false
  install: https://deno.land/x/install/install.sh

go:
  remove_existing: false
  fallback_ver: go1.16.5

dotnet:
  purge_existing_msft_pkg: false
  sdk_version: 6.0

# Installed via Package managers
python:
  state: present

openjdk:
  version: 11
  state: present

# NodeJS via NVM - This will also install latest nodejs stable by default
nvm:
  remove_existing: false
  install: https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh
