- name: Update and Upgrade
  package:
    upgrade: yes
    update_cache: yes

- name: KVM and qemu tools
  package:
    name: "{{ item }}"
    state: "{{ kvm.state }}"  
  loop: 
    - cpu-checker # kvm-ok
    - qemu-kvm
    - libvirt-daemon-system
    - libvirt-clients
    - bridge-utils
    - virt-manager

- name: Add user to libvirt and kvm groups
  ansible.builtin.user:
    name: "{{ lookup('env', 'USER') }}"
    groups: libvirt, kvm
    append: yes
