- name: "minikube - stat"
  stat: 
    path: /usr/bin/minikube
  register: minikube_bin

- when: not minikube_bin.stat.exists or minikube.reinstall == true
  block:
    - name: "minikube - Download"
      get_url:
        url: "{{ minikube.download_link }}"
        dest: /tmp/minikube.deb   
        mode: 0755
    - name: "minikube - Install"
      apt: 
        deb: /tmp/minikube.deb # requires xz-utils        
  always:
    - name: "minikube - Cleanup"
      file:
        path: /tmp/minikube.deb
        state: absent     


# minikube start --driver=kvm2
# minikube config set driver kvm2
# virsh net-list --all
# https://minikube.sigs.k8s.io/docs/drivers/kvm2/
# https://minikube.sigs.k8s.io/docs/tutorials/nvidia_gpu/ 
    

